-- KeywordTracker Database Schema for MySQL/MariaDB
-- Ejecutar en phpMyAdmin

CREATE TABLE User (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191),
  email VARCHAR(191) UNIQUE,
  emailVerified DATETIME(3),
  image VARCHAR(191),
  password VARCHAR(191),
  role VARCHAR(191) NOT NULL DEFAULT 'USER',
  plan VARCHAR(191) NOT NULL DEFAULT 'PREPAID',
  companyName VARCHAR(191),
  taxId VARCHAR(191),
  address VARCHAR(191),
  city VARCHAR(191),
  zipcode VARCHAR(191),
  country VARCHAR(191),
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  lastLogin DATETIME(3),
  registrationIP VARCHAR(191)
);

CREATE TABLE GlobalDomainLock (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  domain VARCHAR(191) NOT NULL UNIQUE,
  addedBy VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE UserBalance (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL UNIQUE,
  balance DOUBLE NOT NULL DEFAULT 0,
  totalSpent DOUBLE NOT NULL DEFAULT 0,
  totalRecharged DOUBLE NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BalanceTransaction (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  type VARCHAR(191) NOT NULL,
  amount DOUBLE NOT NULL,
  balanceBefore DOUBLE NOT NULL,
  balanceAfter DOUBLE NOT NULL,
  description VARCHAR(191),
  metadata TEXT,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_userId_createdAt (userId, createdAt),
  FOREIGN KEY (userId) REFERENCES UserBalance(userId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PricingConfig (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  actionType VARCHAR(191) NOT NULL UNIQUE,
  cost DOUBLE NOT NULL,
  description VARCHAR(191),
  active BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE Project (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  domain VARCHAR(191) NOT NULL,
  country VARCHAR(191) NOT NULL DEFAULT 'ES',
  language VARCHAR(191) NOT NULL DEFAULT 'es',
  userId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Competitor (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  domain VARCHAR(191) NOT NULL,
  projectId VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY Competitor_projectId_domain_key (projectId, domain),
  INDEX Competitor_projectId_idx (projectId),
  FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Keyword (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  term VARCHAR(191) NOT NULL,
  country VARCHAR(191) NOT NULL DEFAULT 'US',
  device VARCHAR(191) NOT NULL DEFAULT 'desktop',
  volume INT,
  projectId VARCHAR(191) NOT NULL,
  dataforseoTaskId VARCHAR(191),
  lastLiveCheck DATETIME(3),
  trackingFrequency VARCHAR(191) NOT NULL DEFAULT 'manual',
  lastAutoCheck DATETIME(3),
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX Keyword_projectId_idx (projectId),
  INDEX Keyword_trackingFrequency_lastAutoCheck_idx (trackingFrequency, lastAutoCheck),
  FOREIGN KEY (projectId) REFERENCES Project(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE KeywordPosition (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  position INT NOT NULL,
  url VARCHAR(500),
  topDomains TEXT,
  date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  keywordId VARCHAR(191) NOT NULL,
  INDEX KeywordPosition_keywordId_date_idx (keywordId, date),
  FOREIGN KEY (keywordId) REFERENCES Keyword(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CachedVolume (
  term VARCHAR(191) NOT NULL PRIMARY KEY,
  volume INT NOT NULL,
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE KeywordReport (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  term VARCHAR(191) NOT NULL,
  country VARCHAR(191) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  data TEXT NOT NULL,
  INDEX KeywordReport_userId_idx (userId),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);
